### ISSUE TITLE
Login Failed, Please Try Again Later

### ISSUE THREAD

**Issue by 89z** [M1n007/node-insta-web-api#20]
Using this program:

~~~js
const Insta = require('node-insta-web-api');
const InstaClient = new Insta();

(async () => {
   await InstaClient.login('srpen6','PASSWORD');
})();
~~~

I get this result:

~~~
D:\Desktop\node_modules\node-insta-web-api\lib\index.js:149
            throw new Error(e)
                  ^

Error: Error: Login Failed, Please Try Again Later.
    at Instagram.login (D:\Desktop\node_modules\node-insta-web-api\lib\index.js:149:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async D:\Desktop\ig.js:7:5
~~~

**Comment by 89z** [comment]
Closing this in favor of my own package:

https://github.com/89z/mech/tree/master/instagram
